### PR TITLE
Close response InputStreams

### LINKED ISSUE #848: Pushing large data set results in Too many open files error
#### Software versions 
Briefcase v1.17.1, macOS 10.15.2

#### Problem description
Pushing a large data set to Aggregate results in Too many open files error.

I believe that these errors cause the push to stop entirely.

I cannot reproduce this on Ubuntu server, which suggests to me that this is a macOS-specific issue. Documentation would be a fine fix for this, but if we can work around it in code, that'd be better.

#### Other information 
```
2019-12-16 11:21:39,249 [ForkJoinPool-1-worker-15] ERROR o.o.briefcase.reused.job.JobsRunner - Error running Job
java.io.UncheckedIOException: java.nio.file.FileSystemException: /Blah/instances/uuid80a92285-f4e8-4d27-a420-37c96cc8df80/submission.xml: Too many open files
	at org.opendatakit.briefcase.reused.UncheckedFiles.newInputStream(UncheckedFiles.java:300)
	at org.opendatakit.briefcase.reused.transfer.AggregateServer.getPushSubmissionRequest(AggregateServer.java:185)
	at org.opendatakit.briefcase.push.aggregate.PushToAggregate.pushSubmissionAndAttachments(PushToAggregate.java:185)
	at org.opendatakit.briefcase.push.aggregate.PushToAggregate.pushSubmissionAndAttachments(PushToAggregate.java:175)
	at org.opendatakit.briefcase.push.aggregate.PushToAggregate.lambda$push$6(PushToAggregate.java:98)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:411)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at org.opendatakit.briefcase.push.aggregate.PushToAggregate.lambda$push$7(PushToAggregate.java:95)
	at org.opendatakit.briefcase.reused.job.Job.lambda$thenAccept$8(Job.java:134)
	at org.opendatakit.briefcase.reused.job.Job.lambda$thenRun$6(Job.java:109)
	at org.opendatakit.briefcase.reused.job.JobsRunner.lambda$launchAsync$1(JobsRunner.java:65)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.nio.file.FileSystemException: /Blah/instances/uuid80a92285-f4e8-4d27-a420-37c96cc8df80/submission.xml: Too many open files
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at org.opendatakit.briefcase.reused.UncheckedFiles.newInputStream(UncheckedFiles.java:298)
	... 29 common frames omitted
2019-12-16 11:21:39,249 [ForkJoinPool-1-worker-5] ERROR o.o.briefcase.reused.job.JobsRunner - Error running Job
java.io.UncheckedIOException: java.nio.file.FileSystemException: /Blah/instances/uuidaa63b5ff-c5b0-4137-9ed4-aebd28b89f1b: Too many open files
	at org.opendatakit.briefcase.reused.UncheckedFiles.list(UncheckedFiles.java:278)
	at org.opendatakit.briefcase.push.aggregate.PushToAggregate.getSubmissionAttachments(PushToAggregate.java:114)
	at org.opendatakit.briefcase.push.aggregate.PushToAggregate.lambda$push$6(PushToAggregate.java:96)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:411)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at org.opendatakit.briefcase.push.aggregate.PushToAggregate.lambda$push$7(PushToAggregate.java:95)
	at org.opendatakit.briefcase.reused.job.Job.lambda$thenAccept$8(Job.java:134)
	at org.opendatakit.briefcase.reused.job.Job.lambda$thenRun$6(Job.java:109)
	at org.opendatakit.briefcase.reused.job.JobsRunner.lambda$launchAsync$1(JobsRunner.java:65)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.nio.file.FileSystemException: /Blah/instances/uuidaa63b5ff-c5b0-4137-9ed4-aebd28b89f1b: Too many open files
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:408)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
	at java.base/java.nio.file.Files.list(Files.java:3694)
	at org.opendatakit.briefcase.reused.UncheckedFiles.list(UncheckedFiles.java:276)
	... 27 common frames omitted
Error pushing a form: java.nio.file.FileSystemException: /Blah/instances/uuid80a92285-f4e8-4d27-a420-37c96cc8df80/submission.xml: Too many open files (see the logs for more info)2019-12-16 11:21:39,249 [ForkJoinPool-1-worker-3] ERROR o.o.briefcase.reused.job.JobsRunner - Error running Job
java.io.UncheckedIOException: java.nio.file.FileSystemException: /Blah/instances/BC2X5M0HFH25MEHPM28IG8HAH: Too many open files
	at org.opendatakit.briefcase.reused.UncheckedFiles.list(UncheckedFiles.java:278)
	at org.opendatakit.briefcase.push.aggregate.PushToAggregate.getSubmissionAttachments(PushToAggregate.java:114)
	at org.opendatakit.briefcase.push.aggregate.PushToAggregate.lambda$push$6(PushToAggregate.java:96)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:411)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at org.opendatakit.briefcase.push.aggregate.PushToAggregate.lambda$push$7(PushToAggregate.java:95)
	at org.opendatakit.briefcase.reused.job.Job.lambda$thenAccept$8(Job.java:134)
	at org.opendatakit.briefcase.reused.job.Job.lambda$thenRun$6(Job.java:109)
	at org.opendatakit.briefcase.reused.job.JobsRunner.lambda$launchAsync$1(JobsRunner.java:65)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.nio.file.FileSystemException: /Blah/instances/BC2X5M0HFH25MEHPM28IG8HAH: Too many open files
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:408)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
	at java.base/java.nio.file.Files.list(Files.java:3694)
	at org.opendatakit.briefcase.reused.UncheckedFiles.list(UncheckedFiles.java:276)
	... 27 common frames omitted
```

### PR DESCRIPTION
**Pull request by poketim**
Closes #848 

#### What has been done to verify that this works as intended?

Code complies, all tests pass, and application runs.

#### Why is this the best possible solution? Were any other approaches considered?

As discussed in the issue, closing the InputStreams after we received the response will help to reduce the number of files opened during a large number of submissions or attachments.

Other approaches were thought of, but would require more re-work/refactoring of existing functionality, where this current solution fits in line with how the code is organized and utilizes InputStreams from the class UncheckedFiles.

I attempted to update and refactor CentralServer using the similar closeInputStream method, but ran into 3 failing unit tests. Code can be found here: https://github.com/timkoon/briefcase/commit/915e262d78ef2e1a32ceb3e3bfedb9346798a0d9
That change may be verified in a separate pull request as issue 848 just references AggregateServer.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The changes should reduce the errors regarding too many files opened. There shouldn't be other impacts to a user's experience. As a note, after the PushToAggregate operation receives a response, it now does some cleaning up (closing input streams and clearing the tracked streams opened).

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.

I don't believe so.

### CODE REVIEW

**Comment by timkoon** [comment]
@getodk/briefcase

**Comment by lognaturel** [comment]
Thank you so much for taking this on, @timkoon, and sorry about the radio silence!

I am unfortunately not very familiar with this code. One thing that I've been wanting to verify is that it indeed is necessary to keep track of all streams and close them all at once at the end. Did you verify that the streams are indeed still open at that point? I would have expected the methods in RequestBuilder at https://github.com/getodk/briefcase/blob/7bb6185e6c3212e9dbe791df32fde25b21ab4a29/src/org/opendatakit/briefcase/reused/http/RequestBuilder.java#L111 and below to close them by using try with resources.

File: src/org/opendatakit/briefcase/push/aggregate/PushToAggregate.java [hunk 1]
```diff
@@ -164,7 +166,13 @@ void pushFormAndAttachments(FormStatus form, List<Path> attachments, RunnerStatu
     }
 
     tracker.trackStartSendingFormAndAttachments(part, parts);
-    Response response = http.execute(server.getPushFormRequest(form.getFormFile(briefcaseDir), attachments));
+    Response<InputStream> response = http.execute(server.getPushFormRequest(form.getFormFile(briefcaseDir), attachments));
+
+    for (InputStream stream : server.getFileStreams()) {
+      closeInputStream(stream);
+    }
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/push/aggregate/PushToAggregate.java:173]:
```suggestion
    server.getFileStreams().forEach(UncheckedFiles::closeInputStream);
```

File: src/org/opendatakit/briefcase/push/aggregate/PushToAggregate.java [hunk 2]
```diff
@@ -186,6 +194,12 @@ void pushSubmissionAndAttachments(Path submissionFile, List<Path> attachments, R
         submissionFile,
         attachments
     ));
+
+    for (InputStream stream : server.getFileStreams()) {
+      closeInputStream(stream);
+    }
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/push/aggregate/PushToAggregate.java:200]:
```suggestion
    server.getFileStreams().forEach(UncheckedFiles::closeInputStream);
```

File: src/org/opendatakit/briefcase/reused/UncheckedFiles.java [hunk 3]
```diff
@@ -301,6 +301,14 @@ public static InputStream newInputStream(Path path, OpenOption... options) {
     }
   }
 
+  public static void closeInputStream(InputStream inputStream) {
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/reused/UncheckedFiles.java:304]: Loving this!

File: src/org/opendatakit/briefcase/reused/transfer/AggregateServer.java [hunk 4]
```diff
@@ -54,10 +55,12 @@
 public class AggregateServer implements RemoteServer {
   private final URL baseUrl;
   private final Optional<Credentials> credentials;
+  private List<InputStream> fileStreams;
 
   public AggregateServer(URL baseUrl, Optional<Credentials> credentials) {
     this.baseUrl = baseUrl;
     this.credentials = credentials;
+    this.fileStreams = new ArrayList<>();
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/reused/transfer/AggregateServer.java:63]:
```suggestion
  private final List<InputStream> fileStreams = new ArrayList<>();

  public AggregateServer(URL baseUrl, Optional<Credentials> credentials, Array) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
```

Comment (ggalmazor) [reply src/org/opendatakit/briefcase/reused/transfer/AggregateServer.java:63]: I suggest making the list `final`, since we're not really want to support reassigning a new value. Also, since this is a property belonging to the internal workings of the class, I think it's OK to assign its value directly in the property declaration.

**Review by ggalmazor — APPROVED** [review]
This is looking good to me, although I have some reservations about making the server class aware of the file streams that some of its requests open. While I believe this alleviates the original issue, I think this should be something that the `Request` should provide instead of the server, along the lines of "file resources opened by this request" so that the HTTP client can close them automatically once the request is sent.

Having said that, I think this doesn't block the release of this PR, although I would consider opening a new PR to address the design improvements I've mentioned above.

I'm also missing tests for this change, which would be nice to have.

**Comment by timkoon** [comment]
> Thank you so much for taking this on, @timkoon, and sorry about the radio silence!
> 
> I am unfortunately not very familiar with this code. One thing that I've been wanting to verify is that it indeed is necessary to keep track of all streams and close them all at once at the end. Did you verify that the streams are indeed still open at that point? I would have expected the methods in RequestBuilder at
> 
> https://github.com/getodk/briefcase/blob/7bb6185e6c3212e9dbe791df32fde25b21ab4a29/src/org/opendatakit/briefcase/reused/http/RequestBuilder.java#L111
> 
> and below to close them by using try with resources. Or is it `Request.body` that never gets closed?

Hi @lognaturel and no problem! In regards to pointing out the line in the RequestBuilder, I would think that approach is optimal when it comes to attachments in the request, but attachments in the request object are actually using `UncheckedFiles.newInputStream`. That method isn't using try-with-resources, so the InputStreams created will need to be closed and are causing the exception in #848 .

Here is where I found Aggregate server is calling that static method:
https://github.com/getodk/briefcase/blob/7bb6185e6c3212e9dbe791df32fde25b21ab4a29/src/org/opendatakit/briefcase/reused/transfer/AggregateServer.java#L160

I haven't verified that the InputStreams are still open while the application is running, but that could possibly be done in an integration test. I did include unit tests to verify Java InputStreams as working as expected, and that `inputStream.close()` closes and deallocates files/resources back to the system.

@ggalmazor Thanks for your review and suggestion. I do like your suggestion of making the Client aware and handle closing InputStreams rather than the Server. After reviewing the flow again, I found the client is already tracking the attachments and their InputStreams, so I would agree that your suggestion is a better alternative and implemented that in the new commits.

**Review by lognaturel — APPROVED** [review]
This looks like a great improvement to me, @timkoon! It's now very clear which streams could be left open. The change feels nicely targeted and tested.

I'll give @ggalmazor a little bit in case he has comments too.

**Comment by ggalmazor** [comment]
(Apologies! will have some cycles for this during the weekend)

File: src/org/opendatakit/briefcase/reused/http/CommonsHttp.java [hunk 5]
```diff
@@ -39,12 +39,16 @@
...
+import org.opendatakit.briefcase.reused.UncheckedFiles;
 import org.opendatakit.briefcase.reused.http.response.Response;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 public class CommonsHttp implements Http {
   private Executor executor;
   private final int maxConnections;
   private final BasicCookieStore cookieStore;
+  private static final Logger LOG = LoggerFactory.getLogger(CommonsHttp.class);
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/reused/http/CommonsHttp.java:51]: I know this is a static member, but I believe we use `logger` as name for this elsewhere.

File: src/org/opendatakit/briefcase/reused/http/CommonsHttp.java [hunk 6]
```diff
@@ -147,6 +151,16 @@ public void unsetProxy() {
       throw new HttpException("The connection has timed out", e);
     } catch (IOException e) {
       throw new UncheckedIOException(e);
+    } finally {
+      try {
+        UncheckedFiles.closeInputStream(request.getBody());
+      } catch (final BriefcaseException exception) {
+        LOG.error("Error: Attempted to close Request.body InputStream, but failed", exception);
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/reused/http/CommonsHttp.java:158]: Not sure if this is something actionable or that would help us help a user having trouble with Briefcase. @timkoon, do you think it would be useful to have this on the log?

File: src/org/opendatakit/briefcase/reused/http/CommonsHttp.java [hunk 7]
```diff
@@ -147,6 +151,16 @@ public void unsetProxy() {
       throw new HttpException("The connection has timed out", e);
     } catch (IOException e) {
       throw new UncheckedIOException(e);
+    } finally {
+      try {
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/reused/http/CommonsHttp.java:155]: I wish we could use try with resources but I guess it's up to the HTTP client's implementation. I recon that this would work as we want.

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java [hunk 8]
```diff
@@ -0,0 +1,65 @@
...
+    inputStream.available();
+  }
+
+  @Test(expected = UncheckedIOException.class)
+  public void closeInputStream_should_throw_exception() throws IOException {
+    InputStream inputStream = mock(InputStream.class);
+    doThrow(new IOException()).when(inputStream).close();
+
+    UncheckedFiles.closeInputStream(inputStream);
+  }
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:64]: @Test(expected = UncheckedIOException.class)
  public void closeInputStream_should_throw_exception() throws IOException {
    InputStream is = new InputStream() {
      @Override
      public int read() throws IOException {
        return 0;
      }

      @Override
      public void close() throws IOException {
        throw new IOException("chuchu");
      }
    };
    UncheckedFiles.closeInputStream(is);
  }

Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:64]: I don't think that this test justifies adding Mockito to the project. I know it's ugly, but the suggested change would take care of the test without Mockito.

```suggestion
  @Test(expected = UncheckedIOException.class)
  public void closeInputStream_should_throw_exception() throws IOException {
    InputStream is = new InputStream() {
      @Override
      public int read() throws IOException {
        return 0;
      }

      @Override
      public void close() throws IOException {
        throw new IOException("chuchu");
      }
    };
    UncheckedFiles.closeInputStream(is);
  }
```

File: build.gradle [hunk 9]
```diff
@@ -62,6 +62,7 @@ dependencies {
   testCompile 'com.github.npathai:hamcrest-optional:2.0.0'
   testCompile 'org.assertj:assertj-swing-junit:3.8.0' // Required for Swing tests
   testCompile "com.github.dreamhead:moco-core:0.12.0"
+  testCompile group: 'org.mockito', name: 'mockito-core', version: '3.4.0'
```
Comment (ggalmazor) [inline build.gradle:65]: I think we need to remove this. See my suggestion about the test that uses this

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java [hunk 10]
```diff
@@ -0,0 +1,65 @@
...
+import java.io.UncheckedIOException;
+import java.nio.file.Path;
+import java.nio.file.Paths;
+
+import org.junit.After;
+import org.junit.Before;
+import org.junit.Test;
+
+
+public class UncheckedFilesTest {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:20]: Kudos for addressing this! My only suggestion would be to change its name to `UncheckedFilesInputStreamTest`.

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+  @Before
+  public void setUp() {
+    tempDir = createTempDirectory("briefcase");
+    temp = Paths.get(tempDir.toString() + "/test.txt");
+    createFile(temp);
+  }
+
+  @After
+  public void tearDown() {
+    deleteRecursive(tempDir);
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:34]: Nice touch! ❤️

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java [hunk 12]
```diff
@@ -0,0 +1,65 @@
...
+  }
+
+  @Test(expected = UncheckedIOException.class)
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:37]: I think this test is not really necessary because then it feels like we should test all the other possible causes for `Files.newInputStream` to throw an `IOException`

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java [hunk 13]
```diff
@@ -0,0 +1,65 @@
...
+  public void newInputStream_should_throw_exception() {
+    UncheckedFiles.delete(temp);
+    UncheckedFiles.newInputStream(Paths.get(tempDir.toString() + "/test.txt"));
+  }
+
+  @Test
+  public void closeInputStream_should_handle_null() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:44]: I think this test is redundant because it's testing what's effectively a NO_OP without side effects.

This IMO is telling us that we need to remove the new `if` block in `closeInputStream` that silently allows for `null` inputStreams to be provided.

File: src/org/opendatakit/briefcase/reused/UncheckedFiles.java [hunk 14]
```diff
@@ -302,6 +302,8 @@ public static InputStream newInputStream(Path path, OpenOption... options) {
   }
 
   public static void closeInputStream(InputStream inputStream) {
+    if (inputStream == null)
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/reused/UncheckedFiles.java:305]: This feels wrong. What's the rationale behind supporting a `null` `inputStream` arg?

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java [hunk 15]
```diff
@@ -0,0 +1,65 @@
...
+import java.nio.file.Path;
+import java.nio.file.Paths;
+
+import org.junit.After;
+import org.junit.Before;
+import org.junit.Test;
+
+
+public class UncheckedFilesTest {
+  private static Path tempDir;
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:21]: No need for this to be static because it's assigned in a `@Before` block
```suggestion
  private Path tempDir;
```

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java [hunk 16]
```diff
@@ -0,0 +1,65 @@
...
+  private Path temp;
+
+
+  @Before
+  public void setUp() {
+    tempDir = createTempDirectory("briefcase");
+    temp = Paths.get(tempDir.toString() + "/test.txt");
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:28]:
```suggestion
    temp = tempDir.resolve("test.txt");
```
We should use the API in `Path` to resolve new children paths.

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java [hunk 17]
```diff
@@ -0,0 +1,65 @@
...
+  }
+
+  @Test
+  public void closeInputStream_should_handle_null() {
+    UncheckedFiles.closeInputStream(null);
+  }
+
+  @Test(expected = IOException.class)
+  public void closeInputStream_should_close() throws IOException {
+    InputStream inputStream = UncheckedFiles.newInputStream(Paths.get(tempDir.toString() + "/test.txt"));
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:50]:
```suggestion
    InputStream inputStream = UncheckedFiles.newInputStream(temp);
```
You can use `temp` here instead of building a new `Path` (also, remember to use `Path.resolve()` ;) )

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java [hunk 18]
```diff
@@ -0,0 +1,65 @@
...
+    // close inputStream
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:51]:
```suggestion
```
I think we can skip this comment

**Review by ggalmazor — CHANGES_REQUESTED** [review]
Thanks for considering my suggestions. I think the implementation is ready, but I've seen some things in the new test class that should be addressed, so I'm requesting some changes there. Feel free to ping me anytime if you think I could help you with that ;)

File: src/org/opendatakit/briefcase/reused/http/CommonsHttp.java (hunk 6 above)
Comment (timkoon) [reply src/org/opendatakit/briefcase/reused/http/CommonsHttp.java:158]: True, it may not be actionable, but in the least, it would give insight into any system issues. I think there's value for the log to be there even though it may be rare that it will trigger.

With the alternative, I don't think there's value if the catch statement does nothing.

File: src/org/opendatakit/briefcase/reused/http/CommonsHttp.java (hunk 5 above)
Comment (timkoon) [reply src/org/opendatakit/briefcase/reused/http/CommonsHttp.java:51]: Sure, it makes sense to be consistent.

File: src/org/opendatakit/briefcase/reused/http/CommonsHttp.java (hunk 7 above)
Comment (timkoon) [reply src/org/opendatakit/briefcase/reused/http/CommonsHttp.java:155]: I agree. There's a chance that the code can be refactored at a later point to possibly accomplish that.

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java (hunk 8 above)
Comment (timkoon) [reply test/java/org/opendatakit/briefcase/reused/UncheckedFilesTest.java:64]: Sure, my thinking was that mockito could be introduced and used in other tests to help cover exception handling or other cases. 

Maybe it can be introduced when a pull request actually contains moderate usage of mockito.

File: src/org/opendatakit/briefcase/reused/UncheckedFiles.java (hunk 14 above)
Comment (timkoon) [reply src/org/opendatakit/briefcase/reused/UncheckedFiles.java:305]: Since it's a static method that could be called in other places, on the off chance that an inputStream is passed and is null, right now, it's not handling the null pointer exception.

The other option could be to update the catch to catch both `catch(NullPointerException | IOException error)`, and throw the UncheckedException.

Otherwise, if you believe it doesn't need to be handled, then I can remove it.

**Comment by timkoon** [comment]
@ggalmazor Do you have a chance to review the updates?

**Comment by lognaturel** [comment]
Thanks so much for thoughtfully addressing the review feedback, @timkoon, and for the ping on this. I'm very happy with this as-is and would like to merge. @ggalmazor I can't seem to do so without your approval, though!

File: src/org/opendatakit/briefcase/reused/http/CommonsHttp.java [hunk 19]
```diff
@@ -147,6 +151,16 @@ public void unsetProxy() {
...
+        UncheckedFiles.closeInputStream(request.getBody());
+      } catch (final BriefcaseException exception) {
+        log.error("Error: Attempted to close Request.body InputStream, but failed", exception);
+      }
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/reused/http/CommonsHttp.java:159]: We don't throw `BriefcaseException` anymore in that method.

```suggestion
      UncheckedFiles.closeInputStream(request.getBody());
```

File: src/org/opendatakit/briefcase/reused/UncheckedFiles.java [hunk 20]
```diff
@@ -301,6 +301,16 @@ public static InputStream newInputStream(Path path, OpenOption... options) {
     }
   }
 
+  public static void closeInputStream(InputStream inputStream) {
+    if (inputStream == null)
+      return;
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/reused/UncheckedFiles.java:306]: This is breaking the existing conventions about allowing nulls.

If we ever receive `null` inputstream we should throw an error here. To avoid them, we should change the calling site, not these utility methods, which operate under narrow set of constraints.

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesInputStreamTest.java [hunk 21]
```diff
@@ -0,0 +1,63 @@
...
+  @After
+  public void tearDown() {
+    deleteRecursive(tempDir);
+  }
+
+  @Test
+  public void closeInputStream_should_handle_null() {
+    UncheckedFiles.closeInputStream(null);
+  }
+
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesInputStreamTest.java:38]: We shouldn't support this now.

```suggestion
```

File: src/org/opendatakit/briefcase/push/aggregate/PushToAggregate.java [hunk 22]
```diff
@@ -21,6 +21,7 @@
 import static org.opendatakit.briefcase.reused.UncheckedFiles.list;
 import static org.opendatakit.briefcase.reused.UncheckedFiles.size;
 
+import java.io.InputStream;
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/push/aggregate/PushToAggregate.java:24]: No need for the `import` now
```suggestion
```

File: src/org/opendatakit/briefcase/push/aggregate/PushToAggregate.java [hunk 23]
```diff
@@ -164,7 +165,8 @@ void pushFormAndAttachments(FormStatus form, List<Path> attachments, RunnerStatu
     }
 
     tracker.trackStartSendingFormAndAttachments(part, parts);
-    Response response = http.execute(server.getPushFormRequest(form.getFormFile(briefcaseDir), attachments));
+    Response<InputStream> response = http.execute(server.getPushFormRequest(form.getFormFile(briefcaseDir), attachments));
+
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/push/aggregate/PushToAggregate.java:169]: I think these are leftover changes from a previous stage of the PR. We don't need the type parameter here anymore.
```suggestion
    Response response = http.execute(server.getPushFormRequest(form.getFormFile(briefcaseDir), attachments));
```

File: src/org/opendatakit/briefcase/push/aggregate/PushToAggregate.java [hunk 24]
```diff
@@ -186,6 +188,7 @@ void pushSubmissionAndAttachments(Path submissionFile, List<Path> attachments, R
         submissionFile,
         attachments
     ));
+
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/push/aggregate/PushToAggregate.java:191]:
```suggestion
```

File: src/org/opendatakit/briefcase/reused/http/CommonsHttp.java (hunk 19 above)
Comment (ggalmazor) [reply src/org/opendatakit/briefcase/reused/http/CommonsHttp.java]: Turns out that I was wrong and we do throw `BriefcaseException`, but it's when trying to access the body of an empty request. I've fixed that in a new commit.

**Review by ggalmazor — APPROVED** [review]

**Comment by ggalmazor** [comment]
Hi, @timkoon, @lognaturel!

MEGA Apologies for the delay in this review. This is not how I like to do things, and I hope you can forgive me.

This PR solves the issue at hand but I think there were a couple of small things we needed to change to align the changes with previous code and make it a smidge simpler if possible. I've gone ahead and applied the changes myself to avoid delaying the PR anymore. I hope you understand.

Other than that: LGTM!

**Comment by lognaturel** [comment]
Thanks both so much! And again, really appreciate your patience, @timkoon. Briefcase v1.18.0 is now out with this fix. 🎉 https://forum.getodk.org/t/odk-briefcase-v1-18/31039
